### ISSUE TITLE
Some code quality metrics would be totally cool

### ISSUE THREAD

**Issue by adam66** [drapostolos/type-parser#33]
It's not really a github thing, but some code quality metrics would be fantastic, so that anal team-mates in corporate dev teams don't get worried about adopting 'unknown' dependencies. 

Not sure how you would do it, but I'd have some test code coverage results, along with the tutorials and the javadoc.

**Comment by drapostolos** [comment]
Hi

Do you mean something like the coverage mentioned in the frontpage (README): https://github.com/drapostolos/type-parser

See below

![image](https://cloud.githubusercontent.com/assets/2085564/26654206/32fcdc3c-4656-11e7-93d1-d3d5d77fa012.png)

**Comment by adam66** [comment]
First time I've come across coveralls.io

so yes, that was what I meant :+1:
