### ISSUE TITLE
How to compile

### ISSUE THREAD

**Issue by shiiraaz** [drapostolos/type-parser#34]
I am not able to use these files as I have to compile these .java file to .class. If i try to compile any single file, it throws dozens of errors. Please help!

**Comment by alexander-poulikakos** [comment]
Sorry for the late response. 

Try
```
git clone https://github.com/drapostolos/type-parser.git
cd type-parser/
./gradlew compileJava
```
Look in the `build/classes` folder

You could also use `./gradlew build`. But I just noticed it complains about javaDoc. I need to fix that.

preferably try to use a dependency management system (ex. Gradle, Maven) and add the following dependency to your project.

Maven

```xml
<dependency>
  <groupId>com.github.drapostolos</groupId>
  <artifactId>type-parser</artifactId>
  <version>0.6.0</version>
</dependency>
```

Gradle

```
compile 'com.github.drapostolos:type-parser:0.6.0'
```

**Comment by drapostolos** [comment]
`./gradlew build` command is fixed.
